### PR TITLE
Fixing autoload

### PR DESCRIPTION
**Pull request by Nikey**

### CODE REVIEW

**Comment by lifo101** [comment]
That change shouldn't be needed. PSR starts at the directory you specify: "src" and appends the class name after it: "src/Lifo/Daemon" automatically. So adding "Lifo/Daemon" to the path is redundant. see: https://getcomposer.org/doc/04-schema.md#psr-4

**Comment by Nikey** [comment]
try it yourself... examples and other stuff aren't working without it
just do a fresh install with composer and you will see that your examples won't work...
also, I needed to change the require_once in example.php to
`__DIR__ . '/../vendor/autoload.php'` instead of `__DIR__ . '/../../../vendor/autoload.php'`

Thanks for your script anyway! It's just awesome

**Comment by lifo101** [comment]
I'll take a look with a fresh install and see what's happening...


-- Jason

**Comment by lifo101** [comment]
Updated the examples to work with or without a parent project composer.json file. See 08fc47b835638afabf893ec0ab09537e9b8b0773

**Comment by lifo101** [comment]
I may have jumped the gun. The examples in one of my projects is not working now. I don't have time for this right now and will look into it more later.

**Comment by lifo101** [comment]
Actually, this is fixed now. See 2bc22e5767f9e8578894723c3b8ed93cafe14909

**Comment by lifo101** [comment]
Turns out the autoload psr-4 was still messing things up due to how I had it configured. I changed it back to psr-0 instead and all works correctly now.

**Pull request closed without merging**
